### ISSUE TITLE
broken travis - confused

### ISSUE THREAD

**Issue by yuxitian** [OHDSI/StudyProtocolSandbox#10]
I'm not sure what's going on. i pulled down a bunch of recent commits but then my git told me i was all of those commits ahead of master.

commit 268fa4878be2b97f7787cc896a92652ff7f93950 from before my change commit 223e1793cc07cb5a4d1b1c3c5b5bd7c4e22df913 is months old for my code for some reason.

now travis is unhappy

**Comment by vojtechhuser** [comment]
closing as obsolete and inactive
