### ISSUE TITLE
An error from 'fetchAllDataFromServer'

### ISSUE THREAD

**Issue by chandryou** [OHDSI/StudyProtocolSandbox#2]
Hi, all.
I'm Seng Chan You from Ajou university, Korea
I'm trying to run the code for the large scale population evidence study. 

We use MS server DB. 
My system information
`
             sysname              release              version             nodename 
           "Windows" "Server >= 2012 x64"         "build 9200"           "ABMI15HO" 
             machine     
            "x86-64"      
`

From fetchAllDataFromServer, I've got the error below.

`fetchAllDataFromServer(connectionDetails = connectionDetails,
                       cdmDatabaseSchema = cdmDatabaseSchema,
                       workDatabaseSchema = workDatabaseSchema,
                       studyCohortTable = studyCohortTable,
                       workFolder = workFolder)`

`Error in FeatureExtraction::getDbCovariateData(connection = connection,  : 
  promise already under evaluation: recursive default argument reference or earlier problems?
In addition: There were 25 warnings (use warnings() to see them)`

The cohort was generated in the study Cohort Table. But I don't know why this error happen. 

The below is the warnings, and It think It isn't serious

`warnings()`
`1: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
2: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
3: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
4: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
5: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
6: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
7: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
8: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
9: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
10: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
11: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
12: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
13: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
14: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
15: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
16: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
17: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
18: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
19: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
20: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
21: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
22: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
23: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
24: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
25: In readChar(pathToSql, file.info(pathToSql)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale`

Thank you!
Chan.

**Comment by schuemie** [comment]
Hi @chandryou !

A wild guess: could you try also providing the oracleTempSchema argument: 
```r
fetchAllDataFromServer(connectionDetails = connectionDetails, cdmDatabaseSchema = cdmDatabaseSchema, workDatabaseSchema = workDatabaseSchema, studyCohortTable = studyCohortTable, workFolder = workFolder, oracleTempSchema = NULL)
```


If that doesn't work, just to be sure you're working on the latest version, could you uninstall the LargeScalePopEst package?:
```r
remove.packages("LargeScalePopEst")
```
Close all instances of R, open one, and reinstall it:
```r
devtools::install_github("ohdsi/StudyProtocols/LargeScalePopEst")
```

**Comment by chandryou** [comment]
It worked! (setting oracleTempleScehma as 'NULL')
It is running now without error message. 
Thanks!!
