### ISSUE TITLE
createSummary error in Large_scale_pop_evidence package

### ISSUE THREAD

**Issue by chandryou** [OHDSI/StudyProtocolSandbox#3]
Hi all,
I have another error in Large_scale_pop_evidence package.

The code below worked well!
`
fetchAllDataFromServer(connectionDetails = connectionDetails,
                       cdmDatabaseSchema = cdmDatabaseSchema,
                       workDatabaseSchema = workDatabaseSchema,
                       oracleTempSchema = NULL,
                       studyCohortTable = studyCohortTable,
                       workFolder = workFolder)
generateAllPopulations(workFolder)
fitAllPredictionModels(workFolder)
`

But the code below made an error
`createSummary(workFolder)`

`Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'E:/OHDSI/Large_scale_pop_evidence/models/knnModels/2556/20170121131455/evaluation/testEvaluationStatistics.csv': No such file or directory`

In this folder, 'testEvaluationStatistics.csv' does not exist.(but other summaries and statitics, distributions exist)

How can I fix this?
Thank you!

**Comment by schuemie** [comment]
Hi @chandryou ,

I'm getting a bit confused. Are you running the [Large scale patient-level prediction study](https://github.com/OHDSI/StudyProtocolSandbox/tree/master/largeScalePrediction) or the [Large scale population-level estimation study](https://github.com/OHDSI/StudyProtocols/tree/master/LargeScalePopEst)?

Cheers,
Martijn

**Comment by chandryou** [comment]
Hi @schuemie 

Sorry for confusing (actually I'm confused too (Too similar names..))

I was running the LargeScalePrediction package for the 'Patient Level Prediction for therapeutically treated depression'

Thanks!
Chan

**Comment by schuemie** [comment]
No problem, I realize they're very similar (even in terms of code to run).

Pulling in @jreps and @PRijnbeek who developed the prediction study package. They should be able to help you further.

**Comment by chandryou** [comment]
Hi all,
I think the error was caused by the dependency for 'gtable' and 'data.table' packages.
Below is the error messages from the files named 'plplog'

`
Training Lasso Logistic Regression model
Error for 2822: Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘gtable’
Error for 2556: Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘gtable’
`

`
Training KNN model
Error for 2551: Error in read.table(file = file, header = header, sep = sep, quote = quote, : first five rows are empty: giving up
`

I'll execute the code again after installing those packages.

**Comment by jreps** [comment]
Thanks for running the study.  Did the code run OK after adding the libraries?

**Comment by chandryou** [comment]
More packages are needed in addition to packages I mentioned. 
I'm struggling to run it! ^^

**Comment by PRijnbeek** [comment]
I am closing this issue since you were able to run.
