### ISSUE TITLE
LargeScalePrediction - runtime errors

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/StudyProtocolSandbox#5]
When running the study package we get the following error:

<code>
************************************************************************************************
INFO [2017-02-13 12:25:20] Starting data extraction
************************************************************************************************
INFO [2017-02-13 12:25:21] Connecting to database
INFO [2017-02-13 12:25:21] Connected
Connecting using PostgreSQL driver
INFO [2017-02-13 12:25:21] Checking work cohort table exists
INFO [2017-02-13 12:25:21] Tested cohort existance
Error executing SQL: Error in rJava::.jcall(s, "Ljava/sql/ResultSet;", "executeQuery", as.character(query)[1]): org.postgresql.util.PSQLException: ERROR: function object_id(character, character) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8

An error report has been created at  /home/jmbanda/OHDSI/largeScalePrediction/errorReport.txt
</code>

Inside the errorReport.txt we get:

<code>
DBMS:
postgresql

Error:
org.postgresql.util.PSQLException: ERROR: function object_id(character, character) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8

SQL:
select OBJECT_ID(N'results_schema.ohdsi_large_scale_prediction', N'U')

R version:
R version 3.3.2 (2016-10-31)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- LargeScalePrediction (0.0.1)
- DatabaseConnector (1.5.0)
- RJDBC (0.2-5)
- rJava (0.9-8)
- DBI (0.5-1)
</code>

This seems like a non-trivial thing we can fix on our side without diving too much in to the code. My guess is that there is some issue with a MSSQL server statement that does not port well to PostgreSQL. I am happy to test alternatives and help debug your changes in case the code has never been fully executed on a Postgre environment.  @jreps  @PRijnbeek

**Comment by schuemie** [comment]
The problem seems to be in [this line](https://github.com/OHDSI/StudyProtocolSandbox/blob/b29ceb2cd17ed08266bc1b0f8ab572fd191a8081/largeScalePrediction/R/fetchAllDataFromServer.R#L67). Here, SQL Server specific statements are used that cannot be translated to other dialects. 

@PRijnbeek , @jreps : I recommend using the [getTableNames](https://github.com/OHDSI/DatabaseConnector/blob/master/R/ListTables.R#L40) function in the [DatabaseConnector](https://github.com/OHDSI/DatabaseConnector) package to list all tables in a schema and check for the existence of a particular table.

**Comment by jreps** [comment]
Thanks, I've made the suggested edit

**Comment by jmbanda** [comment]
Thanks for the fix, it definitely takes care of the previous issue. However, it creates a new one:

<code>
> source('~/OHDSI/largeScalePrediction/stanford_loader.R')
************************************************************************************************
INFO [2017-02-14 11:47:56] Starting data extraction
************************************************************************************************
INFO [2017-02-14 11:47:56] Connecting to database
INFO [2017-02-14 11:47:56] Connected
Connecting using PostgreSQL driver
INFO [2017-02-14 11:47:56] Checking work cohort table exists
INFO [2017-02-14 11:47:56] Inserting risk cohort into cohort table
  |===============================================================================================                                                                                                      |  48%Error executing SQL: Error in .local(conn, statement, ...): execute JDBC update query failed in dbSendUpdate (ERROR: relation "results_schema.ohdsi_large_scale_prediction" does not exist
  Position: 13)

An error report has been created at  /home/jmbanda/OHDSI/largeScalePrediction/errorReport.txt
Error in value[[3L]](cond) : no loop for break/next, jumping to top level
</code>

This happens because the added check is skipped even if the table does not exist. This is the link of code that should be fixed (in the fetchAllDataFromServer.R file:

<code>
exists <- studyCohortTable%in%DatabaseConnector::getTableNames(conn, workDatabaseSchema)

if(is.na(exists)){
.....
</code>

I have created the table manually and now the code seems to be working. I continue this post if any other issues arise.

**Comment by jmbanda** [comment]
The next error comes from the PatientLevelPrediction module I believe:

<code>
INFO [2017-02-14 12:56:21] Inserting Acute myocardial infarction (22/22)
  |=====================================================================================================================================================================================================| 100%
INFO [2017-02-14 12:56:22] Extracting plpData
Connecting using PostgreSQL driver

Constructing the at risk cohort
  |=====================================================================================================================================================================================================| 100%
Executing SQL took 0.0634 secs
Fetching cohorts from server
Loading cohorts took 0.121 secs
Constructing default covariates
  |===========================                                                                                                                                                                          |  13%Error executing SQL: Error in .local(conn, statement, ...): execute JDBC update query failed in dbSendUpdate (ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 439)

An error report has been created at  /home/jmbanda/OHDSI/largeScalePrediction/errorReport.txt
</code>

With the error report being:
<code>
DBMS:
postgresql

Error:
execute JDBC update query failed in dbSendUpdate (ERROR: operator does not exist: timestamp without time zone + integer
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 439)

SQL:
CREATE TEMP TABLE cov_co_365d

AS
SELECT
 DISTINCT cp1.row_id AS row_id,
	CAST(co1.condition_concept_id AS BIGINT) * 1000 + 101 AS covariate_id,
	1 AS covariate_value
  
FROM
 cohort_person cp1
INNER JOIN ohdsiv5_stride6_strict.condition_occurrence co1
	ON cp1.subject_id = co1.person_id
WHERE co1.condition_concept_id != 0


	AND co1.condition_start_date <= cp1.cohort_start_date
	AND co1.condition_start_date >= ( cp1.cohort_start_date +  - 365)

R version:
R version 3.3.2 (2016-10-31)

Platform:
x86_64-redhat-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- LargeScalePrediction (0.0.1)
- DatabaseConnector (1.9.2)
- RJDBC (0.2-5)
- rJava (0.9-8)
- DBI (0.5-1)
- SqlRender (1.2.0)
</code>

If I had to guess I think the TIMESTAMP field needs to be casted before you can add the integer or using DATE_ADD. Also  cp1.cohort_start_date +  - 365  looks a bit funky.

**Comment by PRijnbeek** [comment]
Thanks you are getting closer 👍 

I think this is an error coming from the FeatureExtraction package, @schuemie any thoughts on this?

The + -365 is probably because of the parameterised SQL? I can try if I have the same problems on our PostgreSQL database if that is helpful.

**Comment by jmbanda** [comment]
That would be great, running it on another PostgreSQL database should help narrow it down to a PostgreSQL issue or an issue with our environment.

**Comment by schuemie** [comment]
Hi @jmbanda ,

It seems like your `cohort_start_date` is a `timestamp`, but it should be a `date` field. Can you check?

**Comment by jmbanda** [comment]
Thanks @schuemie! Indeed when I translated the table creation query to PostgreSQL via http://sqlrenderweb.ohdsi.org:2121/ it made the datetime fields into timestamp. I have changed them to date and the code is now running.  I'll post if I find any other error. 

Thanks!

**Comment by jmbanda** [comment]
Minor tweak needed for case sensitive systems: In the file **generateAllPopulations.R** line 61 has to say 'Populations' not lower cased 'populations' (or fix the previous line that creates the folder with an uppercase P). After making this little tweak the code was able to continue running.

**Comment by jmbanda** [comment]
Code completed running with no additional errors! Just one last note:

1) The code produces a summary.csv file and it stops there. Documentation mentions a .zip file, so I believe this should be updated.

**Comment by PRijnbeek** [comment]
This has been solved in a recent update. I am closing this issue.
