### ISSUE TITLE
LargeScalePrediction - Random forest model issue

### ISSUE THREAD

**Issue by pengjin0105** [OHDSI/StudyProtocolSandbox#6]
Hi, this is Eric from Columbia University. I have the following issue when running the Random forest model for the study:

************************************************************************************************
Training random forest model...
Using Random Forest to select features
population loaded- 3195 rows and 3 columns
Train set contains 64.0 outcomes 
Training random forest with mtry= 54
Applying variable importance feature selection...
Error in pyExecp(sprintf("execfile('%s')", as.character(filename)[1])): 
   Traceback (most recent call last):
     File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 344, in __call__
       return self.func(*args, **kwargs)
     File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in __call__
       return [func(*args, **kwargs) for func, args, kwargs in self.items]
     File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in <listcomp>
       return [func(*args, **kwargs) for func, args, kwargs in self.items]
     File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py", line 122, in _parallel_build_trees
       tree.fit(X, y, sample_weight=sample_weight, check_input=False)
     File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\tree\tree.py", line 739, in fit
       X_idx_sorted=X_idx_sorted)
     File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\tree\tree.py", line 199, in fit
       % self.min_samples_split)
   ValueError: min_samples_split must be at least 2 or in (0, 1], got 1
*****************************************************************************************************

Does anyone know what's the problem here? Thanks for any suggestions and help!@PRijnbeek@schuemie

**Comment by PRijnbeek** [comment]
I see you are using Anaconda3 which uses the Python 3.6 version. The PLP Package requires Python 2.7 as mentioned in the Readme.md. This could be the reason for this problem.

Can you try with the other Anaconda version?

**Comment by jreps** [comment]
I think somebody else mentioned before they had issues running the random forest because I had set min_samples_split=1.  I've updated the PatientLevelPrediction package to make min_samples_split=2, so this should resolve the issue if you re-install PatientLevelPrediction.  The 3.6 version may cause issues when we have deep learning models included.

**Comment by pengjin0105** [comment]
Hi Peter and Jenna, thank you so much for the help. I tried Python 2.7 and reinstalled the package. The problem has been solved. Thanks and see you all at the Face-to-Face meeting! @PRijnbeek @jreps
